likelihood:
  params: {'As': {'prior': {'dist': 'uniform', 'min': 1.1010031202900001, 'max': 3.10100312029}, 'ref': 2.10731559362, 'proposal': 0.4001, 'latex': 'A_s'}, 'ns': {'prior': {'dist': 'uniform', 'min': 0.93, 'max': 1.01}, 'ref': 0.96824, 'proposal': 0.04, 'latex': 'n_s'}, 'omch2': {'prior': {'dist': 'uniform', 'min': 0.08, 'max': 0.16}, 'ref': 0.11923, 'proposal': 0.01, 'latex': '\omega_{c}'}, 'ombh2': {'prior': {'dist': 'uniform', 'min': 0.0173, 'max': 0.0272}, 'ref': 0.022447, 'proposal': 0.005, 'latex': '\omega_{b}'}, 'H0': {'prior': {'dist': 'uniform', 'min': 52.0, 'max': 82.0}, 'ref': 67.7, 'proposal': 10.0, 'latex': 'H_0'}, 'w': {'value': -1.0, 'latex': 'w'}, 'logmnu': {'value': -2.0, 'latex': '\log \sum m_{\nu}'}, 'mnu': {'derived': 'lambda logmnu: 10**logmnu', 'latex': '\Sum m_{\nu}'}}
  Nx2PTAngularPowerSpectrum:
    analytic_marginalization: True
    linear_params_filename: /global/cfs/cdirs/cosmosim/slac/jderose/DESIxDES_private/likelihood_configs/noiseless_sims_v2/linear_params_all_lcdm_fixednu_c_kk_no_ia_spline_s0-1-2-3-4_spline_N_2_spline_D_1.5_byk_k2_pade_baryon_spline_N_3_spline_D_0.6_kmm1.0_lcto3_ell_min_kk_0.yaml
    data_vector:
      data_vector_info_filename: /global/cfs/projectdirs/cosmosim/slac/jderose/DESIxDES_private/data/noiseless_sims/fid_lsst_5sbins_y10_nbarpb5.yaml
      spectrum_info: 
        {'c_kk': {'bins0': [0, 1, 2, 3, 4], 'bins1': [0, 1, 2, 3, 4]}}
      scale_cuts :
        {'c_kk': {'0_0': [0, 116.0], '0_1': [0, 169.0], '0_2': [0, 173.0], '0_3': [0, 180.0], '0_4': [0, 182.0], '1_1': [0, 789.0], '1_2': [0, 866.0], '1_3': [0, 925.0], '1_4': [0, 977.0], '2_2': [0, 977.0], '2_3': [0, 1058.0], '2_4': [0, 1134.0], '3_3': [0, 1166.0], '3_4': [0, 1271.0], '4_4': [0, 1415.0]}}
    params: 
      {'c_s_0': {'value': 0.0}, 'c_s_1': {'value': 0.0}, 'c_ds_0': {'value': 0.0}, 'c_ds_1': {'value': 0.0}, 'c_s2_0': {'value': 0.0}, 'c_s2_1': {'value': 0.0}, 'c_L2_0': {'value': 0.0}, 'c_L2_1': {'value': 0.0}, 'c_3_0': {'value': 0.0}, 'c_3_1': {'value': 0.0}, 'c_dt_0': {'value': 0.0}, 'c_dt_1': {'value': 0.0}, 'alpha_s_0': {'value': 0.0}, 'alpha_s_1': {'value': 0.0}, 'delta_z_source_0': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.001}, 'ref': 0.0, 'proposal': 0.001, 'latex': '\Delta z_s^0'}, 'delta_z_source_1': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.001}, 'ref': 0.0, 'proposal': 0.001, 'latex': '\Delta z_s^1'}, 'delta_z_source_2': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.001}, 'ref': 0.0, 'proposal': 0.001, 'latex': '\Delta z_s^2'}, 'delta_z_source_3': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.001}, 'ref': 0.0, 'proposal': 0.001, 'latex': '\Delta z_s^3'}, 'delta_z_source_4': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.001}, 'ref': 0.0, 'proposal': 0.001, 'latex': '\Delta z_s^4'}, 'm_bias_0': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.003}, 'ref': 0.0, 'proposal': 0.001, 'latex': 'm^0'}, 'm_bias_1': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.003}, 'ref': 0.0, 'proposal': 0.001, 'latex': 'm^1'}, 'm_bias_2': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.003}, 'ref': 0.0, 'proposal': 0.001, 'latex': 'm^2'}, 'm_bias_3': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.003}, 'ref': 0.0, 'proposal': 0.001, 'latex': 'm^3'}, 'm_bias_4': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 0.003}, 'ref': 0.0, 'proposal': 0.001, 'latex': 'm^4'}, 'b_kma4_0': {'value': 0.0}, 'b_kma4_1': {'value': 0.0}, 'b_kma4_2': {'value': 0.0}, 'b_kma6_0': {'value': 0.0}, 'b_kma6_1': {'value': 0.0}, 'b_kma6_2': {'value': 0.0}, 'r_pade_0': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 2.0}, 'ref': 1.0, 'proposal': 0.5, 'latex': '\tilde{R}^{0}'}, 'r_pade_1': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 2.0}, 'ref': 1.0, 'proposal': 0.5, 'latex': '\tilde{R}^{1}'}, 'r_pade_2': {'prior': {'dist': 'norm', 'loc': 0.0, 'scale': 2.0}, 'ref': 1.0, 'proposal': 0.5, 'latex': '\tilde{R}^{2}'}}

theory:
  ExpansionHistory:
    use_emulator: False
    emulator_file_names: 
      chi_z: aemulus_nu_tier1_cosmo_only_heft_chiz_emu
      e_z: aemulus_nu_tier1_cosmo_only_heft_ez_emu

  LinearGrowth:
    use_emulator: True
    emulator_file_name: 'aemulus_nu_tier1_cosmo_only_heft_sigma8z_emu'

  RealSpaceMatterPowerSpectrum:
    use_emulator: True
    emulator_file_names: emu_config_dst_irresum.yaml

  RealSpaceBiasedTracerSpectra:
    bias_model: heft #as opposed to CLEFT/linear bias
    use_emulator: True
    emulator_file_names: emu_config_dst_irresum.yaml

  RealSpaceBiasExpansion:
    baryon_z_evolution_model : spline
    p_mm_ct_order : 1
    p_mm_ct_pade: True
    spline_N: 3
    spline_Delta: 0.6
    bias_model: heft
    scale_by_s8z: True
    p_mm_uv_behavior: dmo
  
  DensityShapeIA:
    use_emulator: True
    heft_nla: False
    emulator_file_names: 'emu_p_density_shape.yaml'

  ShapeShapeIA:
    use_emulator: True
    heft_nla: False
    emulator_file_names: 
     - emu_p0_shape_shape.yaml
     - emu_p1_shape_shape.yaml 
     - emu_p2_shape_shape.yaml

  RealSpaceIAExpansion:
    z_evolution_model : spline
    spline_N: 2
    spline_Delta: 1.5
    scale_by_s8z: True
    include_magnification_x_ia: True
    no_ia: True
  
projection:
  k_cutoff: 1.0
  LensingCounterterm:
    lensing_counterterm_order: 3
    mean_model: dmo

  Limber:
    k_cutoff: None

sampler:
  {'NUTS': {'n_steps_warmup': 500, 'n_incr': 50, 'target_r_minus_one': 0.1, 'random_start': False, 'minimize_and_sample': True, 'n_steps_min': 2000}}

#  NUTS:
#    n_steps_warmup: 1000
#    n_steps: 10000
#    random_start: True

output_file: /global/homes/j/jderose/cosmosim/DESIxDES_private/chains/noiseless_sims_v2/fid_lsst_5sbins_y10_nbarpb5_all_lcdm_fixednu_c_kk_no_ia_spline_s0-1-2-3-4_spline_N_2_spline_D_1.5_byk_k2_pade_baryon_spline_N_3_spline_D_0.6_kmm1.0_lcto3_ell_min_kk_0_NUTS.txt
  



    