downsample: 2
n_epochs: 500
n_hidden:
- 8
- 32
- 64
- 128
- 256
n_pcs: 96
output_path: /pscratch/sd/j/jderose/jaxeft/training/trained_models/aemulus_nu_tier1_cosmo_only_p_cleft
param_dataset: params
scale_by_std: true
target: p_cleft
training_filename: /pscratch/sd/j/jderose/jaxeft/training/rs_bias_ia_data_v2.h5
use_asinh: true
