"""
End-to-end pipeline test for Nx2PTCorrelationFunction (config-space likelihood).

Tests that the full gholax pipeline runs correctly with the config-space extension,
producing a finite log-posterior at the reference cosmology.

Requirements:
- NERSC environment with gholax conda environment activated
- dummy_configspace_dv.h5 generated by examples/generate_dummy_datavector.py
- examples/config_configspace_test.yaml

Run from repo root with:
    python examples/test_configspace_pipeline_end_to_end.py

Note: Uses jax.disable_jit() because the Boltzmann code (CLASS) is not JIT-compatible.
      In production, emulator weights replace CLASS and full JIT compilation is supported.
"""
import os
import sys
import jax
import jax.numpy as jnp
import yaml

os.environ["JAX_PLATFORMS"] = "cpu"

# ---- Load config and build model ----
config_path = "examples/config_configspace_test.yaml"
if not os.path.exists(config_path):
    print(f"Config file not found: {config_path}")
    print("Run from the repo root directory.")
    sys.exit(1)

with open(config_path) as f:
    cfg = yaml.safe_load(f)

print("Building model...")
from gholax.util.model import Model
model = Model(cfg)
like = model.likelihoods["Nx2PTCorrelationFunction"]
print("Model built successfully.")

# ---- Check free parameters ----
print(f"\nFree parameters: {model.param_names}")
print(f"Reference values: {dict(zip(model.param_names, model.prior.reference_values))}")

# ---- Run end-to-end pipeline test ----
print("\nRunning end-to-end likelihood evaluation (disable_jit mode)...")
with jax.disable_jit():
    # Evaluate at reference cosmology (zero vector in scaled space = reference values)
    param_vec = jnp.zeros(len(model.prior.reference_values))
    lp = model.log_posterior_scaled_params(param_vec)
    print(f"log_posterior at reference cosmology: {lp:.6e}")

    if jnp.isfinite(lp):
        print("SUCCESS: Pipeline ran end-to-end and produced a finite likelihood.")
    else:
        print("FAIL: log_posterior is not finite.")
        sys.exit(1)

# ---- Verify model vector is physically reasonable ----
print("\nChecking model vector...")
with jax.disable_jit():
    params_all = dict(zip(model.param_names, model.prior.reference_values))
    model_vec, state = like.predict_model(params_all, {}, return_state=True)

print(f"Model vector shape: {model_vec.shape}")
print(f"Model vector finite: {jnp.all(jnp.isfinite(model_vec))}")
print(f"Model vector min: {jnp.min(model_vec):.4e}, max: {jnp.max(model_vec):.4e}")

# Check xi_plus and xi_minus are positive and decreasing
if "xi_pos_0_0_obs" in state:
    xi_pos = state["xi_pos_0_0_obs"]
    xi_neg = state["xi_neg_0_0_obs"]
    print(f"\nxi_+(theta) bin(0,0): {xi_pos}")
    print(f"xi_+(0,0) positive at small angles: {xi_pos[0] > 0}")
    print(f"xi_+(0,0) decreasing: {bool(xi_pos[0] > xi_pos[-1])}")

# ---- Verify chi-squared is near zero (data = theory) ----
print("\nChecking chi-squared (data = theory at reference cosmology)...")
with jax.disable_jit():
    params_all = dict(zip(model.param_names, model.prior.reference_values))
    model_vec, _ = like.predict_model(params_all, {}, return_state=True)
    data = like.observed_data_vector.spectrum_values[like.observed_data_vector.scale_mask]
    diff = model_vec - data
    rel_diff = jnp.max(jnp.abs(diff / data))
    cinv = like.observed_data_vector.cinv
    chi2 = diff @ cinv @ diff

print(f"Max relative difference (theory vs data): {rel_diff:.4e}")
print(f"Chi-squared: {chi2:.4e}")
if chi2 < 1.0:
    print("Chi-squared check PASSED (data consistent with theory at reference cosmology).")
else:
    print("Chi-squared check FAILED (data inconsistent with theory).")

print("\n=== All tests passed ===")